### ISSUE TITLE
new project

### ISSUE THREAD

**Issue by Raboo** [stec-inc/EnhanceIO#114]
@bhansaliakhil 
@deepenmehta85 
And others,

I have suggested in two other forks of this project that we fork it into entirely new project.
https://github.com/lanconnected/EnhanceIO/issues/4
https://github.com/Frontier314/EnhanceIO/issues/2

A new project with the suggested name of EnhanceIO-NG, were all interested parties can take part of the project since commitment to this EnhanceIO seems a bit low and spread around many different forks. This killing EnhanceIO and creating a new project instead and try to direct all pull requests and developers into the new project.

What does everyone think of this?

**Comment by thechile** [comment]
+1 sounds good idea. Don't want EnhanceIO to go the way of Facebooks flashcache which also seems to be shelved indefinitely and doesn't compile on latest kernel versions e.g. 4.5.

**Comment by Raboo** [comment]
I've created a new github organization https://github.com/EnhanceIO.
If anyone wants to be invited to the organization, let me know.

**Comment by elmystico** [comment]
@Raboo this sounds as the reasonable way to go. Did you get any feedback from others (from those forks you've mentioned?). Are they willing to go together?
I'm interested in enhaceio staying alive even though I'm just using it personally (no professional interest). And happy to participate.
But first- what's the response of others Raboo?

**Comment by msva** [comment]
@Raboo can you ping in this issue, when NG-fork become useful (there is empty repo ATM)?
// I've a simple PR to fix buildsystem, and also thinking about additional Makefile rewriting (say, moving CentOS-specific parts into separate include-file ☺)

**Comment by danleepw** [comment]
Strongly agree on that, as the EnhanceIO currently can't be compiled with Kernel 4.4

**Comment by elmystico** [comment]
If there's anyone interested I've got repo with working code with current kernels and systemd/udev fixes.
https://github.com/elmystico/EnhanceIO

**Comment by benramki** [comment]
@Raboo , pls me to your https://github.com/EnhanceIO org

**Comment by Raboo** [comment]
Sorry guys, I've been drowning in work and personal life stuff. But what happened was that I created the github organization EnhanceIO. But no one of the major forks moved their code into the new repo.

**Comment by Raboo** [comment]
@benramki you are added

**Comment by Raboo** [comment]
Closing this issue due to lack of interest/momentum.
If anyone ever wants to use the use the https://github.com/EnhanceIO organization I created, just notify me and I'll add you.
