### ISSUE TITLE
Kernel 3.10.0-514.2.2

### ISSUE THREAD

**Issue by olasemsx** [stec-inc/EnhanceIO#125]
Comiling of the driver doesn't work since this kernel version anymore:
...
/usr/local/src/EnhanceIO/Driver/enhanceio/eio_conf.c:2401:11: Fehler: zu viele Argumente für Funktion »wait_on_bit_lock«
           TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/EnhanceIO/Driver/enhanceio/eio.h:37,
                 from /usr/local/src/EnhanceIO/Driver/enhanceio/eio_conf.c:39:
include/linux/wait.h:1147:1: Anmerkung: hier deklariert
 wait_on_bit_lock(void *word, int bit, unsigned mode)
...
/usr/local/src/EnhanceIO/Driver/enhanceio/eio_conf.c:2414:11: Fehler: zu viele Argumente für Funktion »wait_on_bit_lock«
           TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/mmzone.h:9:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/EnhanceIO/Driver/enhanceio/eio.h:37,
                 from /usr/local/src/EnhanceIO/Driver/enhanceio/eio_conf.c:39:
include/linux/wait.h:1147:1: Anmerkung: hier deklariert
 wait_on_bit_lock(void *word, int bit, unsigned mode)

...

make[2]: *** [/usr/local/src/EnhanceIO/Driver/enhanceio/eio_conf.o] Fehler 1
make[1]: *** [_module_/usr/local/src/EnhanceIO/Driver/enhanceio] Fehler 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.2.2.el7.x86_64'
make: *** [modules] Fehler 2

**Comment by tabokie** [comment]
Kernel 3.10.0-1062.12.1.el7.x86_64 here. Revert this [commit](https://github.com/stec-inc/EnhanceIO/commit/32acf9bf73dcafa3f331ed13adb607cef667d2a0) could solve it.
