### ISSUE TITLE
 ERROR: could not insert 'enhanceio': Exec format error

### ISSUE THREAD

**Issue by andenix** [stec-inc/EnhanceIO#96]
Debian Wheezy,
Kernel SMP 4.0.4 64 bit

install log:

root@arete Driver/enhanceio# make && make install
make -C /lib/modules/4.0.4-goddess/build M=/root/EnhanceIO/Driver/enhanceio modules V=0
make[1]: Entering directory `/usr/src/linux-4.0.4'

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.

  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_conf.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_ioctl.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_main.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_mem.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_policy.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_procfs.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_setlru.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_subr.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_ttc.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_lru.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio_lru.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_fifo.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio_fifo.o
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_rand.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio_rand.o
  Building modules, stage 2.
  MODPOST 4 modules
  CC      /root/EnhanceIO/Driver/enhanceio/enhanceio.mod.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio.ko
  CC      /root/EnhanceIO/Driver/enhanceio/enhanceio_fifo.mod.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio_fifo.ko
  CC      /root/EnhanceIO/Driver/enhanceio/enhanceio_lru.mod.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio_lru.ko
  CC      /root/EnhanceIO/Driver/enhanceio/enhanceio_rand.mod.o
  LD [M]  /root/EnhanceIO/Driver/enhanceio/enhanceio_rand.ko
make[1]: Leaving directory `/usr/src/linux-4.0.4'
make -C /lib/modules/4.0.4-goddess/build M=/root/EnhanceIO/Driver/enhanceio modules V=0
make[1]: Entering directory `/usr/src/linux-4.0.4'

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.

  Building modules, stage 2.
  MODPOST 4 modules
make[1]: Leaving directory `/usr/src/linux-4.0.4'
install -o root -g root -m 0755 -d /lib/modules/4.0.4-goddess/extra/enhanceio/
install -o root -g root -m 0755 enhanceio.ko /lib/modules/4.0.4-goddess/extra/enhanceio/
install -o root -g root -m 0755 enhanceio_rand.ko /lib/modules/4.0.4-goddess/extra/enhanceio/
install -o root -g root -m 0755 enhanceio_fifo.ko /lib/modules/4.0.4-goddess/extra/enhanceio/
install -o root -g root -m 0755 enhanceio_lru.ko /lib/modules/4.0.4-goddess/extra/enhanceio/
depmod -a

**Comment by andenix** [comment]
#modprobe   enhanceio                               
ERROR: could not insert 'enhanceio': Exec format error

**Comment by xjtuwjp** [comment]
maybe you need linux-headers-* package?
see
http://stackoverflow.com/questions/9425523/should-i-care-that-the-symbol-version-dump-is-missing-how-do-i-get-one

2015-06-05 16:13 GMT+02:00 andenix <notifications@github.com>:

**Comment by andenix** [comment]
Yeah thats what I did and it fixed an issue. I apologize for your time.

**Comment by onlyjob** [comment]
Perhaps it would be even better to use [official Debian package](https://tracker.debian.org/pkg/enhanceio).
